  # Importer Bank Peers
  peer0-importer-couchdb:
    image: couchdb:3.1.1
    container_name: peer0-importer-couchdb
    environment:
      - COUCHDB_USER=appbootup
      - COUCHDB_PASSWORD=1234
    volumes:
      - ../../state/peer0-importer-couchdb:/opt/couchdb/data
    ports:
      - 13984:5984
    networks:
      - hyperledger
  peer0-importer:
    image: hyperledger/fabric-peer:2.2.1
    container_name: peer0-importer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer0-importer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:15051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-importer:16051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-importer:15051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-importer:15051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=importer
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-importer-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appbootup
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ../../crypto-config/peerOrganizations/importer/peers/peer0-importer/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/importer/peers/peer0-importer/tls:/etc/hyperledger/fabric/tls
      - ../../state/peer0-importer:/var/hyperledger/production
      - ../../crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ../../scripts/:/scripts/
    ports:
      - 15051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger
  peer1-importer-couchdb:
    image: couchdb:3.1.1
    container_name: peer1-importer-couchdb
    environment:
      - COUCHDB_USER=appbootup
      - COUCHDB_PASSWORD=1234
    volumes:
      - ../../state/peer1-importer-couchdb:/opt/couchdb/data
    ports:
      - 14984:5984
    networks:
      - hyperledger
  peer1-importer:
    image: hyperledger/fabric-peer:2.2.1
    container_name: peer1-importer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer1-importer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:16051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-importer:15051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-importer:16051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1-importer:16051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=importer
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-importer-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appbootup
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ../../crypto-config/peerOrganizations/importer/peers/peer1-importer/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/importer/peers/peer1-importer/tls:/etc/hyperledger/fabric/tls
      - ../../state/peer1-importer:/var/hyperledger/production
      - ../../crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ../../scripts/:/scripts/
    ports:
      - 16051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger