# Carrier Peers
  peer0-carrier-couchdb:
    image: couchdb:3.1.1
    container_name: peer0-carrier-couchdb
    environment:
      - COUCHDB_USER=appbootup
      - COUCHDB_PASSWORD=1234
    volumes:
      - ../../state/peer0-carrier-couchdb:/opt/couchdb/data
    ports:
      - 7984:5984
    networks:
      - hyperledger
  peer0-carrier:
    image: hyperledger/fabric-peer:2.2.1
    container_name: peer0-carrier
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer0-carrier
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-carrier:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-carrier:9051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-carrier:9051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=carrier
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-carrier-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appbootup
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ../../crypto-config/peerOrganizations/carrier/peers/peer0-carrier/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/carrier/peers/peer0-carrier/tls:/etc/hyperledger/fabric/tls
      - ../../state/peer0-carrier:/var/hyperledger/production
      - ../../crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ../../scripts/:/scripts/
    ports:
      - 9051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger
  peer1-carrier-couchdb:
    image: couchdb:3.1.1
    container_name: peer1-carrier-couchdb
    environment:
      - COUCHDB_USER=appbootup
      - COUCHDB_PASSWORD=1234
    volumes:
      - ../../state/peer1-carrier-couchdb:/opt/couchdb/data
    ports:
      - 8984:5984
    networks:
      - hyperledger
  peer1-carrier:
    image: hyperledger/fabric-peer:2.2.1
    container_name: peer1-carrier
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer1-carrier
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-carrier:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-carrier:10051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1-carrier:10051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=carrier
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-carrier-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appbootup
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ../../crypto-config/peerOrganizations/carrier/peers/peer1-carrier/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/carrier/peers/peer1-carrier/tls:/etc/hyperledger/fabric/tls
      - ../../state/peer1-carrier:/var/hyperledger/production
      - ../../crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ../../scripts/:/scripts/
    ports:
      - 10051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger