  # Exporter Bank Peers
  peer0-exporter-couchdb:
    image: couchdb:3.1.1
    container_name: peer0-exporter-couchdb
    environment:
      - COUCHDB_USER=appbootup
      - COUCHDB_PASSWORD=1234
    volumes:
      - ../../state/peer0-exporter-couchdb:/opt/couchdb/data
    ports:
      - 11984:5984
    networks:
      - hyperledger
  peer0-exporter:
    image: hyperledger/fabric-peer:2.2.1
    container_name: peer0-exporter
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer0-exporter
      - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1-exporter:18051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-exporter:17051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-exporter:17051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=exporter
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-exporter-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appbootup
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ../../crypto-config/peerOrganizations/exporter/peers/peer0-exporter/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/exporter/peers/peer0-exporter/tls:/etc/hyperledger/fabric/tls
      - ../../state/peer0-exporter:/var/hyperledger/production
      - ../../crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ../../scripts/:/scripts/
    ports:
      - 17051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger
  peer1-exporter-couchdb:
    image: couchdb:3.1.1
    container_name: peer1-exporter-couchdb
    environment:
      - COUCHDB_USER=appbootup
      - COUCHDB_PASSWORD=1234
    volumes:
      - ../../state/peer1-exporter-couchdb:/opt/couchdb/data
    ports:
      - 12984:5984
    networks:
      - hyperledger
  peer1-exporter:
    image: hyperledger/fabric-peer:2.2.1
    container_name: peer1-exporter
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    environment:
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_DOCKER_ATTACHOUT=true
      - CORE_PEER_ID=peer1-exporter
      - CORE_PEER_LISTENADDRESS=0.0.0.0:18051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-exporter:17051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-exporter:18051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1-exporter:18051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_LOCALMSPID=exporter
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-exporter-couchdb:5984
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=appbootup
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=1234
    volumes:
      - /var/run/:/host/var/run
      - ../../crypto-config/peerOrganizations/exporter/peers/peer1-exporter/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/exporter/peers/peer1-exporter/tls:/etc/hyperledger/fabric/tls
      - ../../state/peer1-exporter:/var/hyperledger/production
      - ../../crypto-config/ordererOrganizations/orderer:/etc/hyperledger/orderers
      - ../../scripts/:/scripts/
    ports:
      - 18051:7051
    depends_on:
      - orderer0
      - orderer1
      - orderer2
    networks:
      - hyperledger
