apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-burst-persistent-volume
spec:
  storageClassName: nfs
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: fs-36d4f24e.efs.us-east-2.amazonaws.com
