apiVersion: v1
kind: Service
metadata:
  name: carrier-ca-service
  labels: {
    component: carrier,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: carrier
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
