apiVersion: v1
kind: Service
metadata:
  name: exporter-bank-ca-service
  labels: {
    component: exporter-bank,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: exporter-bank
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
