apiVersion: v1
kind: Service
metadata:
  name: exporter-ca-service
  labels: {
    component: exporter,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: exporter
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
