apiVersion: v1
kind: Service
metadata:
  name: importer-ca-service
  labels: {
    component: importer,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: importer
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
