apiVersion: v1
kind: Service
metadata:
  name: importer-bank-ca-service
  labels: {
    component: importer-bank,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: importer-bank
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
