apiVersion: v1
kind: Service
metadata:
  name: regulator-ca-service
  labels: {
    component: regulator,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: regulator
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
