name: "default-svc-cluster-local-network"

version: 2.2.1

client:

  organization: regulator

  logging:
    level: info
  
  cryptoconfig:
    path: /host/files/crypto-config

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
    # [Optional]. Used by user store. Not needed if all credentials are embedded in configuration
    # and enrollments are performed elsewhere.
    path: "/tmp/state-store"

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: /tmp/msp

  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  
  tlsCerts:
    systemCertPool: true

channels:

  mainchannel:

    peers:
      peer0-regulator-service:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
  
    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 1000ms
          maxBackoff: 10s
          backoffFactor: 2.0

organizations:
  regulator:
    mspid: regulator
    cryptopath: peerOrganizations/regulator/users/Admin@regulator/msp
    peers:
      - peer0-regulator-service
      - peer1-regulator-service
  carrier:
    mspid: carrier
    cryptopath: peerOrganizations/carrier/users/Admin@carrier/msp
    peers:
      - peer0-carrier-service
      - peer1-carrier-service

orderers:
  _default:
    grpcOptions:
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
  
  orderer0-service:
    grpcOptions:
      ssl-target-name-override: orderer0-service
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem

  
  orderer1-service:
    grpcOptions:
      ssl-target-name-override: orderer1-service
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem

  
  orderer2-service:
    grpcOptions:
      ssl-target-name-override: orderer2-service
      grpc-max-send-message-length: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/ordererOrganizations/orderer/msp/tlscacerts/orderers-ca-7054.pem

peers:

  _default:
    grpcOptions:
      keep-alive-time: 1s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    
  peer0-regulator-service:
    grpcOptions:
      ssl-target-name-override: peer0-regulator-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/peerOrganizations/regulator/msp/tlscacerts/regulator-ca-7054.pem

  peer1-regulator-service:
    grpcOptions:
      ssl-target-name-override: peer1-regulator-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/peerOrganizations/regulator/msp/tlscacerts/regulator-ca-7054.pem

    
  peer0-carrier-service:
    grpcOptions:
      ssl-target-name-override: peer0-carrier-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/peerOrganizations/carrier/msp/tlscacerts/carrier-ca-7054.pem

  peer1-carrier-service:
    grpcOptions:
      ssl-target-name-override: peer1-carrier-service
      grpc.http2.keepalive_time: 15
    
    tlsCACerts:
      path: /host/files/crypto-config/peerOrganizations/carrier/msp/tlscacerts/carrier-ca-7054.pem

entityMatchers:

  peer:
    - pattern: (\w*)peer0-regulator-service-service(\w*)
      urlSubstitutionExp: peer0-regulator-service-service:7051
      sslTargetOverrideUrlSubstitutionExp: peer0-regulator-service-service
      mappedHost: peer0-regulator-service-service

    - pattern: (\w*)peer1-regulator-service-service(\w*)
      urlSubstitutionExp: peer1-regulator-service-service:7051
      sslTargetOverrideUrlSubstitutionExp: peer1-regulator-service-service
      mappedHost: peer1-regulator-service-service

    - pattern: (\w*)peer0-carrier-service-service(\w*)
      urlSubstitutionExp: peer0-carrier-service-service:7051
      sslTargetOverrideUrlSubstitutionExp: peer0-carrier-service-service
      mappedHost: peer0-carrier-service-service

    - pattern: (\w*)peer1-carrier-service-service(\w*)
      urlSubstitutionExp: peer1-carrier-service-service:7051
      sslTargetOverrideUrlSubstitutionExp: peer1-carrier-service-service
      mappedHost: peer1-carrier-service-service

  orderer:
    - pattern: (\w*)orderer0-service(\w*)
      urlSubstitutionExp: orderer0-service:7050
      sslTargetOverrideUrlSubstitutionExp: orderer0-service
      mappedHost: orderer0-service

    - pattern: (\w*)orderer1-service(\w*)
      urlSubstitutionExp: orderer1-servicet:7050
      sslTargetOverrideUrlSubstitutionExp: orderer1-service
      mappedHost: orderer1-service
      
    - pattern: (\w*)orderer2-service(\w*)
      urlSubstitutionExp: orderer2-service:7050
      sslTargetOverrideUrlSubstitutionExp: orderer2-service
      mappedHost: orderer2-service
