apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels: {
    component: web
  }
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: sachinsr/appbootup-web-app:latest